### ISSUE TITLE
Issue installing Error

### ISSUE THREAD

**Issue by mmihir82** [pfitchie/graylog3.Fortigate6xContentPack#3]
Getting error installing:
Installing content pack failed with status: Error: cannot POST https://graylog.ingress.com/api/system/content_packs/e2af204d-a932-423e-9381-def42b84d825/2/installations (500). Could not install content pack with ID: e2af204d-a932-423e-9381-def42b84d825

**Comment by pfitchie** [comment]
You would need to look at your graylog error logs to find what that root cause is.  Also confirm the version your are installing on.

**Comment by mmihir82** [comment]
running version: Graylog 3.0.1+de74b68

**Comment by mmihir82** [comment]
How to make it compatible with current version I have got?

**Comment by pfitchie** [comment]
I do not know, I created it with 3.1.4 so there is likely an issue with earlier versions of graylog and this content pack.
